language: python
cache: pip
python:
  - 3.6
addons:
  apt:
    packages:
      - fonts-ipafont
service: mysql
install:
  - pip install -r requirements.txt
before_script:
  - mysql -u root -e "CREATE DATABASE travis_ci CHARACTER SET utf8mb4"
script:
  - python manage.py migrate
  - python manage.py makemigrations web
  - python manage.py migrate
  - python manage.py test
